// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quizz.DataAccess;

namespace Quizz.DataAccess.Migrations
{
    [DbContext(typeof(QuizzDbContext))]
    partial class QuizzDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Quizz.Entities.Answer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Questionid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("answer_name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("answer_title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.Property<int>("question_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("Questionid");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Quizz.Entities.Exam", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("exam_name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("exam_status")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Exam");
                });

            modelBuilder.Entity("Quizz.Entities.Question", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Examid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("exam_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("question_name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.HasIndex("Examid");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("Quizz.Entities.Answer", b =>
                {
                    b.HasOne("Quizz.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("Questionid");
                });

            modelBuilder.Entity("Quizz.Entities.Question", b =>
                {
                    b.HasOne("Quizz.Entities.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("Examid");
                });
#pragma warning restore 612, 618
        }
    }
}
